# Generated by Django 5.0.7 on 2024-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_owner_stripepayment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='status_payment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус платежа'),
        ),
    ]
