# Generated by Django 5.0.7 on 2024-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_stripepayment_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='course_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id курса'),
        ),
    ]
