# Generated by Django 5.0.7 on 2024-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_subscriptiontocourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontocourse',
            options={'verbose_name': 'Подписка на курс', 'verbose_name_plural': 'Подписки на курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
