# Generated by Django 5.0.7 on 2024-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_subscriptiontocourse_options_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата крайнего обновления'),
        ),
    ]
