# Generated by Django 5.0.7 on 2024-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_course_created_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата крайнего обновления'),
        ),
    ]
