# Generated by Django 5.0.7 on 2024-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_created_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_update',
            new_name='updated_at',
        ),
    ]
